### ISSUE TITLE
Set up stripe

### ISSUE THREAD

**Issue by njal3001** [Garasje-folka/bartstua-frontend#87]

**Comment by njal3001** [comment]
https://firebase.google.com/docs/use-cases/payments

**Comment by WilliamHLe** [comment]
@njal3001 har bare lekt med stripe litt og prøvd å lastet det ned i prosjektet, eneste jeg har gjort er å lage en functions fil. Fortsett gjerne på min branch når du jobber senere. Vi må bruke firestore for å hoste stripe og ikke en egen server som f.eks. express slik nevnt i stripe docs. Kjør `firebase functions:config:set stripe.secret_key=testapikeysomdufinnerpåstripebrukerendin` for å sette opp testnøkkel lokalt.

Fant denne videoen useful: https://www.youtube.com/watch?v=L_ADtp1tWPA
