### ISSUE TITLE
Send booking success email

### ISSUE THREAD

**Issue by njal3001** [Garasje-folka/bartstua-frontend#95]
Create a server side function that sends an email to the user which shows what event they have booked and how many spots.

**Comment by zineth57** [comment]
I found 2 options:

Option 1, https://firebase.google.com/products/extensions/firestore-send-email

Option 2, https://mailtrap.io/blog/sending-emails-with-firebase/

**Comment by zineth57** [comment]
Choosing option 2 to try to implement email service

**Comment by WilliamHLe** [comment]
Så og si ferdig, meldingen som sendes må tilpasses. For å sende epost kall funksjonen `sendMail()`. Per nå kan vi kun sende fra vår egen e-post adresse. Vi må ha tilgang til domenepanelet for å ha en custom e-post adresse, f.eks noreply@bartstua.no eller support@bartstua.no

**Comment by njal3001** [comment]
Okei, kan dere finne ut av hvor vanskelig det er å lage en slik epost?

**Comment by WilliamHLe** [comment]
Tror ikke det skal være så vanskelig. Vi trenger bare tilgang til domenet.

**Comment by njal3001** [comment]
@zineth57 @WilliamHLe noen må lage en funksjon som tar inn et array med booking data og returnerer HTML stringen som skal brukes på bekreftelses mailen. Dere kan teste hvordan mailen kommer til å se ut med HTMLen deres: https://stackoverflow.com/questions/1018078/testing-html-email-rendering

**Comment by njal3001** [comment]
Closing this after we are able to send emails with noreply@bartstua and an email is actually sent on payment completion.
